### PR TITLE
Fix #338: OTEL instrumentation does not work for docker deployment

### LINKED ISSUE #338: OTEL instrumentation does not work for docker deployment
### Affected product(s) and version(s)

ALL

### Environment

ALl

### Steps to reproduce, current result, expected result

Due missing JAVA_OPTS in docker entrypoint command, OTEL javaagent is not inserted

### Log output

_No response_

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: deploy/dockerfile/runtime/docker-entrypoint.sh [hunk 1]
```diff
@@ -7,4 +7,4 @@ liquibase --headless=true --log-level=INFO --changeLogFile="${LB_HOME}/db/change
   --url="${MOBILE_UTILITY_SERVER_DATASOURCE_URL}" \
   update
 
-java -Dserver.port=8000 -jar /mobile-utility-server.war
+java -Dserver.port=8000 ${JAVA_OPTS:-} -jar /mobile-utility-server.war
```
Comment (banterCZ) [inline deploy/dockerfile/runtime/docker-entrypoint.sh:10]: @korbelm Copilot is warning
> Consider verifying that the unquoted JAVA_OPTS expansion behaves as intended when containing multiple options, as unquoted expansion can lead to unexpected word splitting. If word splitting is not desired, you might want to adjust the command accordingly.

Any opinion? Elsewhere, we use `${JAVA_OPTS:-} -jar "${JAR_PATH}"`

**Review by korbelm — APPROVED** [review]
Perfect
