### PR TITLE
Fix #63: Coverity: Dereference null return

### LINKED ISSUE #63: Coverity: Dereference null return
1563169 [Dereference null return value](https://scan7.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_NULL_RETURNS)
If the function actually returns a null value, a NullPointerException will be thrown.

In `com.​wultra.​app.​mobileutilityserver.​rest.​service.​AdminService.​createApplicationCertificate(java.​lang.​String, com.​wultra.​app.​mobileutilityserver.​rest.​model.​request.​CreateApplicationCertificatePemRequest)`: Return value of function which returns null is dereferenced without checking ([CWE-476](http://cwe.mitre.org/data/definitions/476.html))

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: src/main/java/com/wultra/app/mobileutilityserver/rest/service/AdminService.java [hunk 1]
```diff
@@ -198,6 +198,9 @@ public CertificateDetailResponse createApplicationCertificate(String appName, Cr
 
         final PEMParser pemParser = new PEMParser(new StringReader(pem));
         final Object pemInfo = pemParser.readObject();
+        if (pemInfo == null) {
+            throw new IOException("PerParser read null, appName: " + appName);
```
Comment (romanstrobl) [inline src/main/java/com/wultra/app/mobileutilityserver/rest/service/AdminService.java:202]: Typo, should be `PEMParser`.

**Review by romanstrobl — CHANGES_REQUESTED** [review]
Let's fix the typo.
